<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

    Copyright (c) 2013-2015, The SeedStack authors <http://seedstack.org>

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

-->
<definitions targetNamespace="http://seedstack.org/samples/ws/product" name="ProductInfoWSService"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://seedstack.org/samples/ws/product"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema>
            <xsd:import namespace="http://seedstack.org/samples/ws/product"
                        schemaLocation="ProductInfoWS_schema.xsd"/>
        </xsd:schema>
    </types>
    <message name="productInfoByID">
        <part name="parameters" element="tns:productInfoByID"/>
    </message>
    <message name="productInfoByIDResponse">
        <part name="parameters" element="tns:productInfoByIDResponse"/>
    </message>
    <message name="BadProductRequest_Exception">
        <part name="fault" element="tns:BadProductRequest"/>
    </message>
    <portType name="ProductInfoWS">
        <operation name="productInfoByID">
            <input message="tns:productInfoByID"/>
            <output message="tns:productInfoByIDResponse"/>
            <fault message="tns:BadProductRequest_Exception" name="BadProductRequest_Exception"/>
        </operation>
    </portType>
    <binding name="ProductInfoWSPortBinding" type="tns:ProductInfoWS">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="productInfoByID">
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
            <fault name="BadProductRequest_Exception">
                <soap:fault name="BadProductRequest_Exception" use="literal"/>
            </fault>
        </operation>
    </binding>
    <service name="ProductInfoWSService">
        <port name="ProductInfoWSPort" binding="tns:ProductInfoWSPortBinding">
            <soap:address location="/ws/productInfo"/>
        </port>
    </service>
</definitions>

